export const GET_ERRORS = "GET_ERRORS";
export const GET_PAYMENTS = "GET_PAYMENTS";
export const GET_PAYMENT = "GET_PAYMENT";
export const DELETE_PAYMENT = "DELETE_PAYMENT";

export const GET_PAYMENTLOG = "GET_PAYMENTLOG";
export const GET_PAYMENT_INSTALLMENT = "GET_PAYMENT_INSTALLMENT";
export const DELETE_PAYMENT_INSTALLMENT = "DELETE_PAYMENT_INSTALLMENT";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
